version: "3.1"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_UN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_UN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PW}
    depends_on:
      - mongo